### ISSUE TITLE
CC2538 + USB SLIP radio not working.

### ISSUE THREAD

**Issue by nolex90** [contiki-os/contiki#775] opened 2014-08-14 18:14 UTC
I made a custom board for CC2538, but the SLIP-Radio example doesn't working at all.
I made several examples with USB, and it works. I ported to my board the SoC.
When I flash the example program, the USB device can't recognized as CDC-ACM and it doesn't send over UART anything. Modifications:
I made a file with this: (slip-radio-cc2538dk.c)
int
cmd_handler_cc2538(const uint8_t *data, int len)
{
  if(data[0] == '!') {
    if(data[1] == 'C') {
      printf("cc2538_cmd: setting channel: %d\n", data[2]);
    cc2538_rf_channel_set(data[2]);
      return 1;
    } else if(data[1] == 'M') {
		PRINTF("CMD: Got MAC\n");
		memcpy(uip_lladdr.addr, data+2, sizeof(uip_lladdr.addr));
		//rimeaddr_set_node_addr((rimeaddr_t *) uip_lladdr.addr);
		return 1;
	}
  } else if(data[0] == '?') {
    if(data[1] == 'C') {
      uint8_t buf[4];
      printf("cc2538_cmd: getting channel: %d\n", data[2]);
      buf[0] = '!';
      buf[1] = 'C';
      buf[2] = cc2538_rf_channel_get();
      cmd_send(buf, 3);
      return 1;
    }
  }
  return 0;
}

Added the correct includes etc... and the additional defines is:
#undef RF_CHANNEL
#define RF_CHANNEL          25

#define SLIP_ARCH_CONF_USB          1 /** SLIP over UART by default */
#define CC2538_RF_CONF_SNIFFER_USB  0 /** Sniffer out over UART by default */
#define DBG_CONF_USB                0 /** All debugging over UART by default */

Do you have any suggestions?

**Comment by g-oikonomou** [comment] 2015-02-13 10:50
I just finished testing things on a CC2538EM and everything worked as expected. I cannot reproduce this, therefore closing it.

**Closed by g-oikonomou** 2015-02-13 10:50 UTC
Labels: question
